package policy

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCheckedTTLCanonicalVectors(t *testing.T) {
	t.Parallel()
	vectors := loadVectors(t)
	if vectors.Vectors.TTL.VectorName != "ttl-canonical-v1" {
		t.Fatalf("vector name = %q", vectors.Vectors.TTL.VectorName)
	}
	for _, test := range vectors.Vectors.TTL.Accepted {
		test := test
		t.Run("accepted_"+test.Input, func(t *testing.T) {
			t.Parallel()
			seconds, err := ParseTTL(test.Input)
			if err != nil {
				t.Fatalf("ParseTTL(%q) error = %v", test.Input, err)
			}
			if seconds != test.Seconds {
				t.Fatalf("seconds = %d, want %d", seconds, test.Seconds)
			}
			canonical, err := CanonicalTTL(seconds)
			if err != nil {
				t.Fatalf("CanonicalTTL(%d) error = %v", seconds, err)
			}
			if canonical != test.Canonical {
				t.Fatalf("canonical = %q, want %q", canonical, test.Canonical)
			}
		})
	}
	for _, input := range vectors.Vectors.TTL.Rejected {
		input := input
		t.Run("rejected_"+input, func(t *testing.T) {
			t.Parallel()
			if _, err := ParseTTL(input); err == nil {
				t.Fatalf("ParseTTL(%q) succeeded", input)
			}
		})
	}
}

func TestCheckedCanonicalAddArtifact(t *testing.T) {
	t.Parallel()
	policy, candidate := validPair("30m", 1800)
	artifact, err := BuildArtifact(policy, candidate)
	if err != nil {
		t.Fatalf("BuildArtifact() error = %v", err)
	}
	wantCanonical := []byte("add element inet sentinelflow blacklist_ipv4 { 203.0.113.20 timeout 30m }\n")
	if !bytes.Equal(artifact.CanonicalBytes(), wantCanonical) {
		t.Fatalf("canonical bytes = %q, want %q", artifact.CanonicalBytes(), wantCanonical)
	}
	vectors := loadVectors(t)
	if artifact.CanonicalDigest() != vectors.ArtifactDigests.NFTAdd {
		t.Fatalf("canonical digest = %s, checked vector = %s", artifact.CanonicalDigest(), vectors.ArtifactDigests.NFTAdd)
	}
	if artifact.GeneratedDigest() != "sha256:cdf58824141aa6d280b4a5c32c5b2ecc50db68e334b104e4861e6a6421de3303" {
		t.Fatalf("generated digest = %s", artifact.GeneratedDigest())
	}
	if artifact.GeneratedDigest() == artifact.CanonicalDigest() {
		t.Fatal("no-LF generated bytes must remain distinct from canonical bytes")
	}
	if artifact.CanonicalTTLToken() != "30m" || artifact.AST().TTLSeconds() != 1800 || artifact.AST().TargetIPv4() != "203.0.113.20" {
		t.Fatalf("unexpected AST/artifact: token=%s seconds=%d target=%s", artifact.CanonicalTTLToken(), artifact.AST().TTLSeconds(), artifact.AST().TargetIPv4())
	}
}

func TestGeneratedNoncanonicalTTLCanonicalizesWithoutMutation(t *testing.T) {
	t.Parallel()
	policy, candidate := validPair("1800s", 1800)
	original := bytes.Clone(candidate.GeneratedBytes)
	artifact, err := BuildArtifact(policy, candidate)
	if err != nil {
		t.Fatalf("BuildArtifact() error = %v", err)
	}
	if artifact.AST().InputTTLToken() != "1800s" || artifact.CanonicalTTLToken() != "30m" {
		t.Fatalf("tokens = generated %q canonical %q", artifact.AST().InputTTLToken(), artifact.CanonicalTTLToken())
	}
	if !bytes.Equal(artifact.GeneratedBytes(), original) || !bytes.Equal(candidate.GeneratedBytes, original) {
		t.Fatal("generated bytes were silently rewritten")
	}
	if got := string(artifact.CanonicalBytes()); got != "add element inet sentinelflow blacklist_ipv4 { 203.0.113.20 timeout 30m }\n" {
		t.Fatalf("canonical bytes = %q", got)
	}
}

func TestCanonicalSerializerLargestExactUnitAndOneLF(t *testing.T) {
	t.Parallel()
	tests := []struct {
		token string
		secs  uint32
		want  string
	}{
		{"60s", 60, "1m"},
		{"61s", 61, "61s"},
		{"120s", 120, "2m"},
		{"60m", 3600, "1h"},
		{"24h", 86400, "24h"},
	}
	for _, test := range tests {
		test := test
		t.Run(test.token, func(t *testing.T) {
			t.Parallel()
			ast, err := Parse([]byte(command("203.0.113.20", test.token, false)))
			if err != nil {
				t.Fatalf("Parse() error = %v", err)
			}
			if ast.TTLSeconds() != test.secs {
				t.Fatalf("seconds = %d, want %d", ast.TTLSeconds(), test.secs)
			}
			canonical, err := CanonicalBytes(ast)
			if err != nil {
				t.Fatalf("CanonicalBytes() error = %v", err)
			}
			if !bytes.HasSuffix(canonical, []byte(" timeout "+test.want+" }\n")) || bytes.HasSuffix(canonical, []byte("\n\n")) || bytes.Count(canonical, []byte("\n")) != 1 {
				t.Fatalf("canonical output = %q", canonical)
			}
		})
	}
}

func TestStrictParserRejectsNonGrammarInput(t *testing.T) {
	t.Parallel()
	valid := command("203.0.113.20", "30m", false)
	tests := []struct {
		name  string
		input []byte
	}{
		{"empty", nil},
		{"leading space", []byte(" " + valid)},
		{"trailing space", []byte(valid + " ")},
		{"double space", []byte(strings.Replace(valid, "add element", "add  element", 1))},
		{"tab", []byte(strings.Replace(valid, "add element", "add\telement", 1))},
		{"crlf", []byte(valid + "\r\n")},
		{"two lf", []byte(valid + "\n\n")},
		{"comment", []byte(valid + " # trusted")},
		{"semicolon", []byte(valid + ";")},
		{"second statement", []byte(valid + "\n" + valid)},
		{"shell and", []byte(valid + " && id")},
		{"pipe", []byte(valid + " | sh")},
		{"redirection", []byte(valid + " > /tmp/x")},
		{"substitution", []byte(strings.Replace(valid, "203.0.113.20", "$(id)", 1))},
		{"variable", []byte(strings.Replace(valid, "203.0.113.20", "$IP", 1))},
		{"include", []byte("include /tmp/rules")},
		{"delete", []byte(strings.Replace(valid, "add element", "delete element", 1))},
		{"other family", []byte(strings.Replace(valid, " inet ", " ip ", 1))},
		{"other table", []byte(strings.Replace(valid, "sentinelflow", "filter", 1))},
		{"other set", []byte(strings.Replace(valid, "blacklist_ipv4", "other", 1))},
		{"missing timeout", []byte("add element inet sentinelflow blacklist_ipv4 { 203.0.113.20 }")},
		{"range", []byte(strings.Replace(valid, "203.0.113.20", "203.0.113.20-203.0.113.30", 1))},
		{"multiple address", []byte(strings.Replace(valid, "203.0.113.20", "203.0.113.20, 203.0.113.21", 1))},
		{"ipv6", []byte(strings.Replace(valid, "203.0.113.20", "2001:db8::1", 1))},
		{"bom", append([]byte{0xef, 0xbb, 0xbf}, []byte(valid)...)},
		{"nul", append([]byte(valid), 0)},
		{"invalid utf8", append([]byte(valid), 0xff)},
		{"oversized", bytes.Repeat([]byte("a"), MaxGeneratedBytes+1)},
		{"uppercase ttl", []byte(strings.Replace(valid, "30m", "30M", 1))},
		{"leading zero ttl", []byte(strings.Replace(valid, "30m", "030m", 1))},
		{"decimal ttl", []byte(strings.Replace(valid, "30m", "1.5h", 1))},
		{"space ttl", []byte(strings.Replace(valid, "30m", "30 m", 1))},
	}
	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			if _, err := Parse(test.input); err == nil {
				t.Fatalf("Parse(%q) succeeded", test.input)
			}
		})
	}
}

func TestParserRejectsNoncanonicalOrNonGlobalIPv4(t *testing.T) {
	t.Parallel()
	for _, address := range []string{
		"203.0.113.020", "203.0.113", "203.0.113.256", "0.0.0.0", "127.0.0.1",
		"169.254.1.1", "224.0.0.1", "255.255.255.255",
	} {
		address := address
		t.Run(address, func(t *testing.T) {
			t.Parallel()
			if _, err := Parse([]byte(command(address, "30m", false))); err == nil {
				t.Fatalf("address %q was accepted", address)
			}
		})
	}
	// IsGlobalUnicast deliberately does not implement M5-004 protected-range
	// policy. Documentation and private targets remain parseable ASTs, then are
	// blocked by the later protected-target gate outside this package.
	for _, address := range []string{"203.0.113.20", "10.0.0.1"} {
		if _, err := Parse([]byte(command(address, "30m", false))); err != nil {
			t.Fatalf("syntax-stage Parse(%q) error = %v", address, err)
		}
	}
}

func TestTTLCheckedBounds(t *testing.T) {
	t.Parallel()
	accepted := map[string]uint32{"1m": 60, "60s": 60, "1440m": 86400, "24h": 86400, "86400s": 86400}
	for input, want := range accepted {
		got, err := ParseTTL(input)
		if err != nil || got != want {
			t.Errorf("ParseTTL(%q) = %d, %v; want %d", input, got, err, want)
		}
	}
	for _, input := range []string{"0s", "59s", "86401s", "1441m", "25h", "99999h", "18446744073709551615h", "+60s", "-60s"} {
		if _, err := ParseTTL(input); err == nil {
			t.Errorf("ParseTTL(%q) succeeded", input)
		}
	}
	for _, seconds := range []uint32{0, 59, 86401, ^uint32(0)} {
		if _, err := CanonicalTTL(seconds); err == nil {
			t.Errorf("CanonicalTTL(%d) succeeded", seconds)
		}
	}
}

func TestBuildArtifactConsistencyFailures(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		mutate func(*Policy, *Candidate)
		code   ErrorCode
	}{
		{"policy schema", func(p *Policy, _ *Candidate) { p.SchemaVersion = "response-policy-v2" }, ErrorSchema},
		{"candidate schema", func(_ *Policy, c *Candidate) { c.SchemaVersion = "shell-v1" }, ErrorSchema},
		{"action", func(p *Policy, _ *Candidate) { p.Action = "allow_ip" }, ErrorAction},
		{"policy target", func(p *Policy, _ *Candidate) { p.TargetIPv4 = "203.0.113.21" }, ErrorTargetMismatch},
		{"candidate target", func(_ *Policy, c *Candidate) { c.TargetIPv4 = "203.0.113.21" }, ErrorTargetMismatch},
		{"ttl token", func(_ *Policy, c *Candidate) { c.TimeoutToken = "1800s" }, ErrorCandidateMismatch},
		{"policy ttl", func(p *Policy, _ *Candidate) { p.TTLSeconds = 60 }, ErrorTTLMismatch},
		{"missing evidence", func(p *Policy, c *Candidate) { p.EvidenceIDs = nil; c.EvidenceIDs = nil }, ErrorEvidence},
		{"candidate evidence", func(_ *Policy, c *Candidate) { c.EvidenceIDs = []string{testEvidenceID(2)} }, ErrorEvidence},
		{"duplicate evidence", func(p *Policy, c *Candidate) {
			ids := []string{testEvidenceID(1), testEvidenceID(1)}
			p.EvidenceIDs = ids
			c.EvidenceIDs = ids
		}, ErrorEvidence},
		{"unordered evidence", func(p *Policy, c *Candidate) {
			ids := []string{testEvidenceID(2), testEvidenceID(1)}
			p.EvidenceIDs = ids
			c.EvidenceIDs = ids
		}, ErrorEvidence},
		{"invalid evidence", func(p *Policy, c *Candidate) { ids := []string{"not-a-uuid"}; p.EvidenceIDs = ids; c.EvidenceIDs = ids }, ErrorEvidence},
	}
	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			policy, candidate := validPair("30m", 1800)
			test.mutate(&policy, &candidate)
			_, err := BuildArtifact(policy, candidate)
			assertErrorCode(t, err, test.code)
		})
	}
}

func TestArtifactAccessorsAreDefensive(t *testing.T) {
	t.Parallel()
	policy, candidate := validPair("30m", 1800)
	artifact, err := BuildArtifact(policy, candidate)
	if err != nil {
		t.Fatal(err)
	}
	generated := artifact.GeneratedBytes()
	canonical := artifact.CanonicalBytes()
	evidence := artifact.EvidenceIDs()
	generated[0] = 'x'
	canonical[0] = 'x'
	evidence[0] = testEvidenceID(9)
	if artifact.GeneratedBytes()[0] != 'a' || artifact.CanonicalBytes()[0] != 'a' || artifact.EvidenceIDs()[0] != testEvidenceID(1) {
		t.Fatal("artifact state was mutable through an accessor")
	}
	candidate.GeneratedBytes[0] = 'x'
	policy.EvidenceIDs[0] = testEvidenceID(9)
	if artifact.GeneratedBytes()[0] != 'a' || artifact.EvidenceIDs()[0] != testEvidenceID(1) {
		t.Fatal("artifact retained caller-owned slices")
	}
}

func TestErrorsDoNotEchoGeneratedBytes(t *testing.T) {
	t.Parallel()
	const secretShapedInput = "add element inet sentinelflow blacklist_ipv4 { $(super-secret) timeout 30m }"
	_, err := Parse([]byte(secretShapedInput))
	if err == nil || strings.Contains(err.Error(), secretShapedInput) || strings.Contains(err.Error(), "super-secret") {
		t.Fatalf("unsafe parser error: %v", err)
	}
	var typed *Error
	if !errors.As(err, &typed) || typed.Code != ErrorSyntax {
		t.Fatalf("error = %T %v", err, err)
	}
}

func TestParseAcceptsNoLFOrExactlyOneLF(t *testing.T) {
	t.Parallel()
	base := command("203.0.113.20", "30m", false)
	for _, input := range []string{base, base + "\n"} {
		ast, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse(%q) error = %v", input, err)
		}
		canonical, err := CanonicalBytes(ast)
		if err != nil {
			t.Fatal(err)
		}
		if string(canonical) != base+"\n" {
			t.Fatalf("canonical = %q", canonical)
		}
	}
}

type contractVectors struct {
	ArtifactDigests struct {
		NFTAdd string `json:"nft_add_artifact_sha256"`
	} `json:"artifact_digests"`
	Vectors struct {
		TTL struct {
			VectorName string `json:"vector_name"`
			Accepted   []struct {
				Input     string `json:"input"`
				Seconds   uint32 `json:"seconds"`
				Canonical string `json:"canonical"`
			} `json:"accepted"`
			Rejected []string `json:"rejected"`
		} `json:"ttl_canonical_v1"`
	} `json:"vectors"`
}

func loadVectors(t *testing.T) contractVectors {
	t.Helper()
	path := filepath.Join("..", "..", "contracts", "vectors", "contract_vectors_v1.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read checked vectors: %v", err)
	}
	var vectors contractVectors
	if err := json.Unmarshal(data, &vectors); err != nil {
		t.Fatalf("decode checked vectors: %v", err)
	}
	if vectors.ArtifactDigests.NFTAdd == "" || len(vectors.Vectors.TTL.Accepted) == 0 || len(vectors.Vectors.TTL.Rejected) == 0 {
		t.Fatal("checked nft/TTL vectors are incomplete")
	}
	return vectors
}

func validPair(token string, seconds uint32) (Policy, Candidate) {
	generated := []byte(command("203.0.113.20", token, false))
	ids := []string{testEvidenceID(1), testEvidenceID(2)}
	return Policy{
			SchemaVersion: PolicySchemaVersion,
			Action:        ActionBlockIP,
			TargetIPv4:    "203.0.113.20",
			TTLSeconds:    seconds,
			EvidenceIDs:   append([]string(nil), ids...),
		}, Candidate{
			SchemaVersion:  CandidateSchemaVersion,
			TargetIPv4:     "203.0.113.20",
			TimeoutToken:   token,
			EvidenceIDs:    append([]string(nil), ids...),
			GeneratedBytes: generated,
		}
}

func command(address, ttl string, newline bool) string {
	result := "add element inet sentinelflow blacklist_ipv4 { " + address + " timeout " + ttl + " }"
	if newline {
		return result + "\n"
	}
	return result
}

func testEvidenceID(number int) string {
	return fmt.Sprintf("00000000-0000-0000-0000-%012x", number)
}

func assertErrorCode(t *testing.T, err error, code ErrorCode) {
	t.Helper()
	if err == nil {
		t.Fatalf("error = nil, want %s", code)
	}
	var typed *Error
	if !errors.As(err, &typed) || typed.Code != code {
		t.Fatalf("error = %T %v, want code %s", err, err, code)
	}
}
