package nftvalidate

import (
	"bytes"
	"errors"
	"net/netip"
	"strings"
	"testing"
)

const validCandidate = "add element inet sentinelflow blacklist_ipv4 { 203.0.113.20 timeout 30m }"

func TestCanonicalizeGoldenArtifact(t *testing.T) {
	t.Parallel()
	artifact, err := Canonicalize([]byte(validCandidate), 1800)
	if err != nil {
		t.Fatalf("Canonicalize() error = %v", err)
	}
	wantCanonical := validCandidate + "\n"
	if got := string(artifact.CanonicalBytes()); got != wantCanonical {
		t.Fatalf("canonical = %q, want %q", got, wantCanonical)
	}
	if artifact.CanonicalDigest() != "sha256:866cc23464d760a1de172d66ccd076c6a7915c6011a75d47dc93224bbe5539e6" {
		t.Fatalf("canonical digest = %s", artifact.CanonicalDigest())
	}
	if artifact.GeneratedDigest() != "sha256:cdf58824141aa6d280b4a5c32c5b2ecc50db68e334b104e4861e6a6421de3303" {
		t.Fatalf("generated digest = %s", artifact.GeneratedDigest())
	}
	if artifact.GeneratedDigest() == artifact.CanonicalDigest() {
		t.Fatal("generated bytes without LF must have a distinct digest")
	}
	if artifact.TargetIPv4() != "203.0.113.20" || artifact.TTLSeconds() != 1800 ||
		artifact.InputTTLToken() != "30m" || artifact.CanonicalTTLToken() != "30m" {
		t.Fatalf("unexpected artifact fields: target=%s seconds=%d input=%s canonical=%s",
			artifact.TargetIPv4(), artifact.TTLSeconds(), artifact.InputTTLToken(), artifact.CanonicalTTLToken())
	}
}

func TestTTLContractAndLargestExactCanonicalUnit(t *testing.T) {
	t.Parallel()
	accepted := []struct {
		input     string
		seconds   uint32
		canonical string
	}{
		{"60s", 60, "1m"},
		{"61s", 61, "61s"},
		{"1800s", 1800, "30m"},
		{"30m", 1800, "30m"},
		{"3600s", 3600, "1h"},
		{"24h", 86400, "24h"},
	}
	for _, test := range accepted {
		test := test
		t.Run(test.input, func(t *testing.T) {
			t.Parallel()
			input := strings.Replace(validCandidate, "30m", test.input, 1)
			artifact, err := Canonicalize([]byte(input), test.seconds)
			if err != nil {
				t.Fatalf("Canonicalize(%q) error = %v", test.input, err)
			}
			if artifact.CanonicalTTLToken() != test.canonical ||
				!bytes.HasSuffix(artifact.CanonicalBytes(), []byte(" timeout "+test.canonical+" }\n")) {
				t.Fatalf("canonical token/bytes = %q / %q", artifact.CanonicalTTLToken(), artifact.CanonicalBytes())
			}
		})
	}
	for _, token := range []string{"0s", "59s", "1441m", "25h", "01m", "1M", "1.5h", "1 m", "86401s"} {
		token := token
		t.Run("reject_"+token, func(t *testing.T) {
			t.Parallel()
			input := strings.Replace(validCandidate, "30m", token, 1)
			if _, err := Canonicalize([]byte(input), 1800); err == nil {
				t.Fatalf("Canonicalize(%q) succeeded", token)
			}
		})
	}
}

func TestCanonicalizeRejectsPolicyTTLMismatchAndInvalidPolicy(t *testing.T) {
	t.Parallel()
	for _, policyTTL := range []uint32{60, 1799, 1801, 86400} {
		_, err := Canonicalize([]byte(validCandidate), policyTTL)
		assertCode(t, err, ErrorTTLMismatch)
	}
	for _, policyTTL := range []uint32{0, 59, 86401, ^uint32(0)} {
		_, err := Canonicalize([]byte(validCandidate), policyTTL)
		assertCode(t, err, ErrorTTL)
	}
}

func TestCanonicalizeRejectsEverythingOutsideClosedGrammar(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name  string
		input []byte
	}{
		{"empty", nil},
		{"leading space", []byte(" " + validCandidate)},
		{"trailing space", []byte(validCandidate + " ")},
		{"double space", []byte(strings.Replace(validCandidate, "add element", "add  element", 1))},
		{"tab", []byte(strings.Replace(validCandidate, "add element", "add\telement", 1))},
		{"crlf", []byte(validCandidate + "\r\n")},
		{"two lf", []byte(validCandidate + "\n\n")},
		{"embedded lf", []byte(strings.Replace(validCandidate, " timeout", "\ntimeout", 1))},
		{"comment", []byte(validCandidate + " # allow")},
		{"semicolon", []byte(validCandidate + ";")},
		{"second command", []byte(validCandidate + "\n" + validCandidate)},
		{"shell and", []byte(validCandidate + " && id")},
		{"shell or", []byte(validCandidate + " || true")},
		{"pipeline", []byte(validCandidate + " | sh")},
		{"redirection", []byte(validCandidate + " >/tmp/x")},
		{"substitution", []byte(strings.Replace(validCandidate, "203.0.113.20", "$(id)", 1))},
		{"backticks", []byte(strings.Replace(validCandidate, "203.0.113.20", "`id`", 1))},
		{"variable", []byte(strings.Replace(validCandidate, "203.0.113.20", "$IP", 1))},
		{"include", []byte("include /tmp/rules")},
		{"delete", []byte(strings.Replace(validCandidate, "add element", "delete element", 1))},
		{"replace", []byte(strings.Replace(validCandidate, "add element", "replace element", 1))},
		{"flush", []byte("flush table inet sentinelflow")},
		{"other family", []byte(strings.Replace(validCandidate, " inet ", " ip ", 1))},
		{"other table", []byte(strings.Replace(validCandidate, "sentinelflow", "filter", 1))},
		{"other set", []byte(strings.Replace(validCandidate, "blacklist_ipv4", "other", 1))},
		{"missing timeout", []byte("add element inet sentinelflow blacklist_ipv4 { 203.0.113.20 }")},
		{"timeout flag", []byte(strings.Replace(validCandidate, "timeout 30m", "flags timeout 30m", 1))},
		{"cidr", []byte(strings.Replace(validCandidate, "203.0.113.20", "203.0.113.0/24", 1))},
		{"range", []byte(strings.Replace(validCandidate, "203.0.113.20", "203.0.113.20-203.0.113.30", 1))},
		{"multiple targets", []byte(strings.Replace(validCandidate, "203.0.113.20", "203.0.113.20, 203.0.113.21", 1))},
		{"ipv6", []byte(strings.Replace(validCandidate, "203.0.113.20", "2001:db8::1", 1))},
		{"bom", append([]byte{0xef, 0xbb, 0xbf}, []byte(validCandidate)...)},
		{"nul", append([]byte(validCandidate), 0)},
		{"invalid utf8", append([]byte(validCandidate), 0xff)},
		{"unicode whitespace", []byte(strings.Replace(validCandidate, "add element", "add\u00a0element", 1))},
		{"oversized", bytes.Repeat([]byte{'a'}, MaxCandidateBytes+1)},
	}
	for _, test := range tests {
		test := test
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			if _, err := Canonicalize(test.input, 1800); err == nil {
				t.Fatalf("Canonicalize(%q) succeeded", test.input)
			}
		})
	}
}

func TestCanonicalizeRejectsNoncanonicalOrNonGlobalAddress(t *testing.T) {
	t.Parallel()
	for _, target := range []string{
		"203.0.113.020", "203.0.113", "203.0.113.256", "0.0.0.0", "127.0.0.1",
		"169.254.1.1", "224.0.0.1", "255.255.255.255",
	} {
		target := target
		t.Run(target, func(t *testing.T) {
			t.Parallel()
			input := strings.Replace(validCandidate, "203.0.113.20", target, 1)
			if _, err := Canonicalize([]byte(input), 1800); err == nil {
				t.Fatalf("Canonicalize(target=%q) succeeded", target)
			}
		})
	}
}

func TestCanonicalizeAcceptsNoLFOrOneLFOnly(t *testing.T) {
	t.Parallel()
	for _, input := range []string{validCandidate, validCandidate + "\n"} {
		artifact, err := Canonicalize([]byte(input), 1800)
		if err != nil {
			t.Fatalf("Canonicalize(%q) error = %v", input, err)
		}
		if string(artifact.CanonicalBytes()) != validCandidate+"\n" {
			t.Fatalf("canonical = %q", artifact.CanonicalBytes())
		}
	}
}

func TestValidateRequiresProtectedTargetAuthorization(t *testing.T) {
	t.Parallel()
	base, live := loadOwnedSchemaContracts(t)

	_, err := Validate(Input{
		GeneratedCandidate: []byte(validCandidate),
		PolicyTTLSeconds:   1800,
		BaseContract:       base,
		LiveSchema:         live,
	})
	assertCode(t, err, ErrorTargetDenied)

	called := false
	_, err = Validate(Input{
		GeneratedCandidate: []byte(validCandidate),
		PolicyTTLSeconds:   1800,
		AuthorizeTarget: func(target netip.Addr) bool {
			called = true
			return target.String() == "198.51.100.7"
		},
		BaseContract: base,
		LiveSchema:   live,
	})
	assertCode(t, err, ErrorTargetDenied)
	if !called {
		t.Fatal("target authorizer was not called")
	}
}

func TestValidateRejectsProtectedAndBroadTargetsBeforeSchema(t *testing.T) {
	t.Parallel()
	for _, target := range []string{"10.0.0.1", "203.0.113.20"} {
		input := strings.Replace(validCandidate, "203.0.113.20", target, 1)
		_, err := Validate(Input{
			GeneratedCandidate: []byte(input),
			PolicyTTLSeconds:   1800,
			AuthorizeTarget:    func(netip.Addr) bool { return false },
			// Deliberately invalid: a denied protected target must not advance to
			// the owned-schema gate.
			BaseContract: nil,
			LiveSchema:   nil,
		})
		assertCode(t, err, ErrorTargetDenied)
	}

	broad := strings.Replace(validCandidate, "203.0.113.20", "0.0.0.0/0", 1)
	_, err := Validate(Input{
		GeneratedCandidate: []byte(broad),
		PolicyTTLSeconds:   1800,
		AuthorizeTarget:    func(netip.Addr) bool { return true },
	})
	assertCode(t, err, ErrorCandidateSyntax)
}

func TestErrorsNeverEchoUntrustedInput(t *testing.T) {
	t.Parallel()
	secretShaped := []byte("add element inet sentinelflow blacklist_ipv4 { $(do-not-log-me) timeout 30m }")
	_, err := Canonicalize(secretShaped, 1800)
	if err == nil || strings.Contains(err.Error(), "do-not-log-me") || strings.Contains(err.Error(), string(secretShaped)) {
		t.Fatalf("unsafe error = %v", err)
	}
}

func TestArtifactAccessorsAreDefensive(t *testing.T) {
	t.Parallel()
	input := []byte(validCandidate)
	artifact, err := Canonicalize(input, 1800)
	if err != nil {
		t.Fatal(err)
	}
	input[0] = 'x'
	generated := artifact.GeneratedBytes()
	canonical := artifact.CanonicalBytes()
	generated[0] = 'x'
	canonical[0] = 'x'
	if artifact.GeneratedBytes()[0] != 'a' || artifact.CanonicalBytes()[0] != 'a' {
		t.Fatal("artifact bytes are caller-mutable")
	}
}

func assertCode(t *testing.T, err error, want ErrorCode) {
	t.Helper()
	if err == nil {
		t.Fatalf("error = nil, want %s", want)
	}
	var typed *Error
	if !errors.As(err, &typed) || typed.Code != want {
		t.Fatalf("error = %T %v, want code %s", err, err, want)
	}
}
