package nftvalidate

import (
	"crypto/sha256"
	"encoding/hex"
	"net/netip"
)

const (
	GrammarVersion   = "nft-blacklist-v1"
	ParserVersion    = "nft-blacklist-parser-v1"
	ValidatorVersion = "owned-schema-validator-v1"

	Family       = "inet"
	Table        = "sentinelflow"
	BlacklistSet = "blacklist_ipv4"
	SetType      = "ipv4_addr"

	LiveSchemaVersion = "nft-base-chain-live-v1"
	GatewayChain      = "gateway_input"
	GatewayPort       = 8080

	PinnedBaseChainRawDigest = "sha256:2d6476f6297f9b135032934bc557110541bae7eb2fe16fe29be70d20d0f4c488"
	PinnedLiveSchemaDigest   = "sha256:d5582a75817d349b12f292d212483bb0c2a5db66afde7d73c6d11050a5eb5997"

	MinTTLSeconds     uint32 = 60
	DefaultTTLSeconds uint32 = 1800
	MaxTTLSeconds     uint32 = 86400

	MaxCandidateBytes    = 256
	MaxBaseContractBytes = 16 * 1024
	MaxLiveSchemaBytes   = 16 * 1024
)

type ErrorCode string

const (
	ErrorCandidateSyntax ErrorCode = "candidate_syntax_invalid"
	ErrorTarget          ErrorCode = "target_invalid"
	ErrorTargetDenied    ErrorCode = "target_not_authorized"
	ErrorTTL             ErrorCode = "ttl_invalid"
	ErrorTTLMismatch     ErrorCode = "ttl_policy_mismatch"
	ErrorBaseContract    ErrorCode = "base_contract_invalid"
	ErrorLiveSchema      ErrorCode = "live_schema_invalid"
	ErrorSchemaDigest    ErrorCode = "owned_schema_digest_mismatch"
)

// Error contains only a stable code. It never echoes untrusted candidate or
// schema bytes into logs.
type Error struct{ Code ErrorCode }

func (e *Error) Error() string {
	if e == nil {
		return "nftables validation rejected"
	}
	return "nftables validation rejected: " + string(e.Code)
}

func reject(code ErrorCode) error { return &Error{Code: code} }

// TargetAuthorizer is the mandatory handoff from the preceding protected-IP
// gate. The callback receives only a parsed canonical IPv4 address. A nil
// callback, false result, or target mismatch fails closed.
type TargetAuthorizer func(netip.Addr) bool

// Input is the complete pure-validation input. GeneratedCandidate is untrusted
// model output. PolicyTTLSeconds is the already schema-checked policy value.
// BaseContract and LiveSchema are separately obtained trusted-path/read-back
// bytes; both pinned digests must match.
type Input struct {
	GeneratedCandidate []byte
	PolicyTTLSeconds   uint32
	AuthorizeTarget    TargetAuthorizer
	BaseContract       []byte
	LiveSchema         []byte
}

// Artifact binds the exact generated bytes to the deterministic canonical
// bytes. Its state is immutable through the public API.
type Artifact struct {
	target          netip.Addr
	ttlSeconds      uint32
	inputTTLToken   string
	canonicalToken  string
	generated       []byte
	generatedDigest string
	canonical       []byte
	canonicalDigest string
}

func (a Artifact) Target() netip.Addr        { return a.target }
func (a Artifact) TargetIPv4() string        { return a.target.String() }
func (a Artifact) TTLSeconds() uint32        { return a.ttlSeconds }
func (a Artifact) InputTTLToken() string     { return a.inputTTLToken }
func (a Artifact) CanonicalTTLToken() string { return a.canonicalToken }
func (a Artifact) GeneratedBytes() []byte    { return append([]byte(nil), a.generated...) }
func (a Artifact) GeneratedDigest() string   { return a.generatedDigest }
func (a Artifact) CanonicalBytes() []byte    { return append([]byte(nil), a.canonical...) }
func (a Artifact) CanonicalDigest() string   { return a.canonicalDigest }

// SchemaProof records the two distinct pinned nftables schema identities.
// The raw bootstrap digest must never be substituted for the canonical live
// structure digest.
type SchemaProof struct {
	baseContractDigest string
	liveSchemaDigest   string
	liveCanonical      []byte
}

func (p SchemaProof) BaseContractDigest() string { return p.baseContractDigest }
func (p SchemaProof) LiveSchemaDigest() string   { return p.liveSchemaDigest }
func (p SchemaProof) LiveCanonicalBytes() []byte {
	return append([]byte(nil), p.liveCanonical...)
}

// Result is produced only after grammar, policy TTL, protected-target
// authorization, and both owned-schema checks pass.
type Result struct {
	artifact Artifact
	schema   SchemaProof
}

func (r Result) Artifact() Artifact  { return cloneArtifact(r.artifact) }
func (r Result) Schema() SchemaProof { return cloneSchemaProof(r.schema) }

func cloneArtifact(value Artifact) Artifact {
	value.generated = append([]byte(nil), value.generated...)
	value.canonical = append([]byte(nil), value.canonical...)
	return value
}

func cloneSchemaProof(value SchemaProof) SchemaProof {
	value.liveCanonical = append([]byte(nil), value.liveCanonical...)
	return value
}

func digest(data []byte) string {
	sum := sha256.Sum256(data)
	return "sha256:" + hex.EncodeToString(sum[:])
}
